import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import Navigation from "../components/layout/Navigatios";
import Footer from "../components/layout/Footer";

const nunitoSansSerif = Nunito({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${nunitoSansSerif.className} antialiased`}>
        <div className="absolute inset-0 -z-10 overflow-hidden">
          {/* Left big circle */}
          <div
            className="
              absolute
              -top-80
              -left-100
              w-180
              h-180
              rounded-full
              border
              border-white
            "
          />

          {/* Right medium circle */}
          <div
            className="
              absolute
              -top-80
              -right-100
              w-180
              h-180
              rounded-full
              border
              border-white
            "
          />

          {/* Bottom subtle circle */}
          <div
            className="
              absolute
              -top-85
              -right-105
              w-200
              h-200
              rounded-full
              border
              border-white
            "
          />
        </div>
        {/* Navigation Section  */}
        <Navigation />
        {children}
        {/* Footer Section */}
        <Footer />
      </body>
    </html>
  );
}
